spring:
  application:
    name: restaurantetudibaum
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:restaurantetudibaum;DB_CLOSE_DELAY=-1;AUTO_RECONNECT=TRUE;MODE=MySQL;
    username: ${USUARIO_DB_RESTAURANTE:thiago}
    password: ${SENHA_DB_RESTAURANTE:123}
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: none
    defer-datasource-initialization: true
    show-sql: true
  sql:
    init:
      mode: always
  h2:
    console:
      enabled: true
  messages:
    encoding: ISO-8859-1
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
#springdoc:
#  api-docs:
#    path: /api-docs
#    enabled: true
#  swagger-ui:
#    path: /swagger-ui.html
#    enabled: true
#    disable-swagger-default-url: true
server:
  servlet:
    context-path: /restaurantetudibaum